### ISSUE TITLE
Memory leak in fabric 1.19 version

### ISSUE THREAD

**Issue by m-m-0-0** [GizmoTheMoonPig/luggage#10]
I'm running a fabric server with a few (20-30) mods installed, and I'm running into some memory leak problems in the client.
I traced it back to this mod using Spark.
I also tried to start a single player world with only this mod, its dependencies and spark installed, and it's exibithing the same behaviour.

I don't have any clear step to reproduce this, but what I do is spawn some Luggages, fill them up with some stuff, pick them up, throw the item to the ground and spawn a couple of them again. This seems to always use up all the available JVM memory in a few minutes.

here's a spark heapsummary made right when it starts lag spiking: 
    https://spark.lucko.me/hx5GFp8ftE

installed mods:
- fabric-api-0.57.0+1.19.jar
- spark-1.9.26-fabric.jar
- luggage-1.4.2-fabric.jar
    
let me know if you need additional information, thanks!

**Comment by GizmoTheMoonPig** [comment]
Thank you for reporting this, we'll look into a fix as soon as we can. 
In the meantime, would you be willing to test the forge version as well? I'm curious if this is an issue on both versions or just fabric. I would do it myself but I'm gonna be unavailable for a little bit

**Comment by m-m-0-0** [comment]
Sure! I'll get to it as soon as I got some time.

**Comment by m-m-0-0** [comment]
Doesn't seem to happen in Forge
here's the spark heapsummary after about 20 minutes, tried to recreate the same conditions as in the fabric one roughly:
    https://spark.lucko.me/9MpB0GsE6G

hope this helps!

**Comment by GizmoTheMoonPig** [comment]
Awesome, really glad to hear this isn't an issue on both versions. 
One last thing before we can go about debugging this correctly, what mods were you playing with on fabric? Was it just the 3 you mentioned initially, or did you have other mods loaded up as well? I'll need a whole list if there's any others. We want to identify any possible mod conflicts and fix those if it's not just the mod itself acting up.

**Comment by m-m-0-0** [comment]
So, I noticed the issue while playing with these mods installed (luggage currently removed):
![image](https://user-images.githubusercontent.com/13752773/180106597-d1cd3266-c0e1-4734-9598-cf4c00ea2e93.png)

Then I tried just leaving the three mods I mentioned in the first post and the problem remained, so I don't suppose it's a mod conflict.

**Comment by AlphaMode** [comment]
Can you try the latest version I think it might possibly fix it

**Comment by GizmoTheMoonPig** [comment]
Gonna assume this is no longer an issue since I havent heard anything about it. If its still a problem let me know, I take stuff like this very seriously. Thanks for reporting!
