### ISSUE TITLE
Recipe broken in Fabric 1.19 version

### ISSUE THREAD

**Issue by chimericdream** [GizmoTheMoonPig/luggage#11]
It looks like the tags being used in the default recipe do not exist, so you are able to craft luggage with an empty crafting table.

![2022-07-24 15_54_36-Minecraft_ 1 19 - Singleplayer](https://user-images.githubusercontent.com/198075/180665548-1d43ddaa-3436-40de-a55f-14ae52ba7bab.png)

![2022-07-24 15_54_56-Minecraft_ 1 19 - Singleplayer](https://user-images.githubusercontent.com/198075/180665549-b4f0dfc7-bb9f-4a35-a502-983e0bd6d6ce.png)

![2022-07-24 15_55_06-Minecraft_ 1 19 - Singleplayer](https://user-images.githubusercontent.com/198075/180665550-377ac506-79fc-4d86-9d85-f7e0fa1ecbdb.png)

I confirmed this with a minimal modpack that included only REI, Luggage, and their respective required libraries.
![image](https://user-images.githubusercontent.com/198075/180665581-0e5a021a-a888-492b-8338-3db0673f974b.png)

**Comment by AlphaMode** [comment]
Fixed in latest release
