### ISSUE TITLE
Feature Request: Command to collect / wait

### ISSUE THREAD

**Issue by Grumpey102** [GizmoTheMoonPig/luggage#12]
Hey,

I use this mod to have a bigger inventory while spelunking and it's rather annoying that this creature always immediately runs to any dropped items. Because of it, it breaks the line of sight to the next block and I restart mining that block a few times. It's also rather a jumpscare when you're mining, and a creature would instantly run full speed past you and blocks your vision for a moment. It would be nice if we had another whistle command to make luggage start collecting / wait for that command, so that I can mine a few blocks, then press the key / use the item / enter the command, however u want to implement it (I'd like a key / command) Luggage runs and collects, then comes back, I command it to wait and then mine again / go somewhere else.

**Comment by GizmoTheMoonPig** [comment]
Thats actually a neat idea, ill think about how to implement something like that when I get a chance. Thank you for the suggestion!

**Comment by BrainSlugs83** [comment]
Can you make it like (vanilla) parrots?  Where you just right click on them and get them to sit down? -- also can you give us an option/setting to change it's speed. -- It's so fast that it's crazy, and it's always running off, and won't stay put.

**Comment by GizmoTheMoonPig** [comment]
I can't do right clicking, I already use that for opening the inventory. Shift right click won't work either, since thats how you pick it up as an item. I'm thinking maybe I need some sort of item or another keybind to make them sit/stop colelcting if that's something people really want. 
Speed can be changed via attributes, but I can look into making it a bit slower.

**Comment by BrainSlugs83** [comment]
Hmmm... that's fair on right clicking... though... maybe you could make it so that when the menu is open, that it doesn't run away? -- That's really annoying when it does that because it just rips you out of the inventory screen. -- I think that would solve my biggest complaint.

**Comment by GizmoTheMoonPig** [comment]
Sure, that's super easy to do. Surprised I didn't implement that already

**Comment by BrainSlugs83** [comment]
Though... now that I think about it... it would still be good to have a way to make the chest stop / hold still -- a new keybind is fine IMO.

**Comment by Grumpey102** [comment]
I have *no idea* how hart or easy it is to implement keybinds. But when a modder gives me free reign I often put related functions on the same button, but with another button pressed.

Like for example Xaero's mini map and world map have the option to display all the waypoints and then toggle them in minimap and the ingame 3d waypoint seperately. So I have that on Y, ctrl+Y and ctrl+Shift.

Currently I have luggage on the key left of 1 (^ in Germany, I think ~ in America?). The one above TAB. I could imagine Alt+[that key] to turn luggage on and off.

I also noticed after I fell loads of trees (everything full with sapplings and sticks), that luggage ran away, came back, ran away, came back, etc. Always running back instead to the next item took way more time. Maybe that came because I placed luggage down after I removed the trees, I don't know.

Oh and it had problems coming out of the water next to my tree farm for some reason, but I don't know why. If that issue persists I'll make a new issue post though. Or maybe it waited for items that sank down but didn't come up, that also happens at times.

If you want me to make new issues for the various things I'm describing, tell me, I will do it :) I suppose it's annoying for you when one issue thread has multiple things to change

**Comment by GizmoTheMoonPig** [comment]
It's fairly easy to add new keybinds. The hard part is writing the code to go along with it. 
I'll look into improving the item fetching in lots of different ways. People seem to have a lot of problems with it. Making the mob smart is not an easy task, but I'll do my best to improve it. Thought my system worked pretty well, guess not lol
I've been rather swamped with my real life job and another project I'm working on with a friend, but I'll find some time to work on improving this mod :)
I appreciate all of the feedback from everybody. I wasn't expecting do many people to actually use this mod, I just made it as a request from someone. Thank you so much for helping this mod grow and improve, ill do my best to make this little guy the best he can be :)

**Comment by BrainSlugs83** [comment]
Holy crap -- I just realized you could right click on it while sneaking and it picks it back up and into your inventory?!

Definitely add a readme.md 😅  (Do you want help with that? -- I could throw one together if it's helpful.)

But for me, with the new AI stuff you are building, I think that fixes everything -- like I probably don't need a command for it to wait if I can just disappear it into my inventory! -- maybe add popping noise when it happens so that it's obvious that it happened? (At first I thought it was a bug, because it just disappeared when I tried to open it, and I was freaking out because I didn't realize it was in my inventory! 😅)

**Comment by GizmoTheMoonPig** [comment]
I'm surprised people don't know that's a thing, it was a thing in openblocks and I have it on the curseforge page. I do really need to add a Readme though (and an issue template, forge vs fabric is always important!) I'll probably do that tonight after I get off work

**Comment by Grumpey102** [comment]
yeah x) I'm on fabric btw (well, quilt, but same thing) so I'm excited for the fabric update :P

**Comment by GizmoTheMoonPig** [comment]
Fabric is hopefully coming soon, I already released the update on forge and I've let the fabric maintainer know, so hopefully you guys will see the update soon!

**Comment by GizmoTheMoonPig** [comment]
Fabric update was pushed today! Apologies for the delay, enjoy!
