### ISSUE TITLE
Whistle has no concurrency detection

### ISSUE THREAD

**Issue by BrainSlugs83** [GizmoTheMoonPig/luggage#13]
Holding down the whistle key for a second (because it can take a second for the whistle to happen... so it just seems natural)... can cause like 100 whistles to all happen at once... -- it feels like this causes some frame drops too when it happens.

I suggest adding some kind of concurrency detection (i.e. ignore the whistle key until the whistle is over -- that way if you hold it down, it will still whistle over and over... but not 100 whistles all at once).

**Comment by GizmoTheMoonPig** [comment]
Which version are you playing on? I fixed the whistle spam back in the 1.18 version, should be on 1.19 as well.

**Comment by BrainSlugs83** [comment]
In MultiMC it says the version is "NONE".  For Minecraft, I'm using 1.19.
The MD5 hash of the file I downloaded matches this one, so I guess I'm using 1.4.2:
![image](https://user-images.githubusercontent.com/5217366/186267425-4fd62c01-4ed0-431e-9571-4da3951407b6.png)

**Comment by BrainSlugs83** [comment]
This is also happening in 1.4.3 (Fabric).

**Comment by GizmoTheMoonPig** [comment]
oh its because the fix isnt on fabric. I'll get in touch with the fabric maintainer, and we'll get that fixed soon

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in the latest fabric version. Let me know if it isn't and we'll get it fixed
