### ISSUE TITLE
Free Luggage glitch?

### ISSUE THREAD

**Issue by BrainSlugs83** [GizmoTheMoonPig/luggage#15]
According to OpenBlocks the recipe for the Luggage should be this:
![image](https://user-images.githubusercontent.com/5217366/186260152-dd90a636-0cc8-4546-8dbd-eda48679d7d4.png)

1. Is that correct for this mod? And if so, can you document it in the readme.md? -- it doesn't show up in the in-game recipe book either (despite saying recipe unlocked in the toast messages it's just not in there...  is it possible to add it to the recipe book?) 
![image](https://user-images.githubusercontent.com/5217366/186261422-f69d57b0-5393-4fc4-a5b6-3eabe9442ded.png)

2. But more importantly: any time you remove all items from the crafting table (i.e. you finish crafting a pickaxe, and then remove all the items), it will let you craft the luggage from nothing for free (see animated gif below where I'm just addding and removing a dirt block...):
![Luggage-Crafting-Issue](https://user-images.githubusercontent.com/5217366/186265405-bb04c317-75e6-4d32-8bb6-6376d1d3b3c0.gif)

**Comment by GizmoTheMoonPig** [comment]
1. The recipe is still the same, yes. I'll build a readme as soon as I get some time to (I also really need an issue template; I don't know which issues are fabric exclusive). It should show up in the recipe book, not sure whats happening there, unless it relates to the 2nd point. 
2. Speaking of, is this fabric? Im pretty sure this was fixed in 1.4.3, make sure youre up to date

**Comment by BrainSlugs83** [comment]
Yes, it's fabric. -- The latest version I see for 1.19 is 1.4.2.

I'm currently unable to go past Minecraft 1.19 due to other dependencies at the moment.

**Comment by GizmoTheMoonPig** [comment]
1.4.3 should work on 1.19.0, its located here: https://www.curseforge.com/minecraft/mc-mods/luggage/files/3901069

**Comment by BrainSlugs83** [comment]
Ohhhhhh! -- the +4 is that it supports more than one version... I did not know that! -- Let me try it.

**Comment by GizmoTheMoonPig** [comment]
yup, its marked for all 1.19 versions. Nothing game-breaking really happened between the versions so I can safely support all 3 with 1 build

**Comment by BrainSlugs83** [comment]
Looks like this is fixed in 1.4.3 for Fabric!
