### ISSUE TITLE
[1.19.1 Forge] AI gets hung up often

### ISSUE THREAD

**Issue by EvergreenSystems** [GizmoTheMoonPig/luggage#17]
### Forge or Fabric

Forge

### Mod Version

1.5.1

### Bug Description

When using the luggage to pick up items off the floor, it will often get frozen just standing, looking at the items on the ground without moving to pick them up (regardless of how full it is, this occurs even when it is empty). Moving it via summon whistle sometimes fixes it, but I would say it only actually picks up about 30% of stuff on the ground before freezing up

### Steps to Reproduce

1. Drop lots of stuff on the ground (I mainly use the luggage when quarrying, so a lot of stuff ends up on the floor)
2. Observe the luggage as it moves to pick up the items

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by EvergreenSystems** [comment]
![2022-10-12_20 18 13](https://user-images.githubusercontent.com/23658767/195476753-405fd516-30de-4513-b72a-0a5612a0eaa0.png)

The thousand-foot stare

**Comment by GizmoTheMoonPig** [comment]
I greatly increased the pickup range, didnt have it get stuck once while running it through many different tests. Hope this fixes the issue, i'll have a new build out tomorrow. Appreciate the report!
