### ISSUE TITLE
[1.19.2] Issue with Luggages Version of Forge Tags

### ISSUE THREAD

**Issue by pokesmells** [GizmoTheMoonPig/luggage#18]
### Forge or Fabric

Fabric

### Mod Version

 luggage-1.4.3.jar

### Client Log

https://gist.github.com/Poke097/81dbbcfd14026f7389442ed8ffaaaa4b

### Crash Report (if applicable)

https://gist.github.com/Poke097/a5f592cf4e9c0c45f4982b9c28f947cb

### Bug Description

Apparently the Forge tags being out of date is leading to the old version taking precedence which is causing the EntityType Tags to be non existent, which lead to a server crash when using a separate mod (Twilight Forest), I've gone ahead and linked the comment from the Twilight forest issue to this one.

### Steps to Reproduce

1. Go into the snowy forest

2. Encounter a yeti

3. Will crash game randomly

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Poke097** [comment]
https://github.com/TeamTwilight/twilightforest-fabric/issues/#131

**Comment by pokesmells** [comment]
https://github.com/TeamTwilight/twilightforest-fabric/issues/131#issuecomment-1319066781

**Comment by AlphaMode** [comment]
Fixed in latest release
