### ISSUE TITLE
[Bug] The whistle button can be held down causing earpiercing sound

### ISSUE THREAD

**Issue by Vapaman** [GizmoTheMoonPig/luggage#2]
**Description**
The whistle button can be held down (has to be bound to a key on a keyboard) similar to throwing a bunch of items in succesion. This causes the whistle sound to play continuously and teleports luggage in a rapid succession.

**Intended behaviour:**
Pressing the whistle button only triggers the whistle once, even when held down.

**Comment by Vapaman** [comment]
Mod version: 1.3
Forge version: 40.1.25

**Comment by GizmoTheMoonPig** [comment]
fixed in da5b20d6559fb92143e477df19c1110c3d665440. Sorry about that oversight! I'll have a build pushed to curseforge very shortly. Thank you for the report!
