### ISSUE TITLE
Cannot hit any mob/player after trying to punch a luggage.

### ISSUE THREAD

**Issue by StargazingKitsune** [GizmoTheMoonPig/luggage#21]
### Forge or Fabric

Fabric

### Mod Version

v1.5.1

### Client Log

https://gist.github.com/StargazingKitsune/9eb968455bc328cf5d941a35074dca39

### Bug Description

Unable to hit mobs and other players with fists/physical attacks but can still use ranged weaponry.

### Steps to Reproduce

I punched a luggage from the luggage mod that belonged to someone else and I cannot hit mobs physically except with ranged weapons.

I picked up the luggage and own it now, I'm not sure if that also contributes anything, but my companions have also been affected by the mob by being unable to hit mobs with physical weaponry/their fists.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by YuWhee** [comment]
Yeah its made the game unplayable, it happens after I dropped my sword into luggage, put it back into my inventory. Only happened when I was around people

**Comment by Manaether** [comment]
https://github.com/GizmoTheMoonPig/luggage/blob/fabric/1.19.x/src/main/java/com/gizmo/luggage/mixin/client/MinecraftMixin.java#L50

Shouldn't we add `shouldCancel.remove()` in an else statement to reassign the boolean to it's default value, for now it seem to toggle to true thus ignoring all mob after trying to hit luggage

**Comment by AlphaMode** [comment]
Fixed in latest release
