### ISSUE TITLE
The recipe is blank

### ISSUE THREAD

**Issue by Tyquelynn** [GizmoTheMoonPig/luggage#22]
### Forge or Fabric

Fabric

### Mod Version

1.5.1 and 1.4.3 for 1.19.2

### Client Log

https://gist.github.com/CrazyModderFabric/69afe43ebec3d0482e2fc54bc037a454

### Crash Report (if applicable)

https://gist.github.com/CrazyModderFabric/34904eb4f7300357a43b42c74058e163

### Bug Description

The recipe for fabric 1.19.2 is blank. Using roughly enough items and clicking "automated shapeless crafting" from create mod crashes the game.

Here's what the recipe looks like:
![2022-12-24_09 33 51](https://user-images.githubusercontent.com/97486907/209446865-fbced1b6-2dac-478a-9f65-1e1c57893bf2.png)

### Steps to Reproduce

1. Install create and roughly enough items.
2. Open recipe.
3. Bonus: select "automated shapeless crafting" and the game will crash.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Should work in 1.5.2. This was a mod conflict from create
