### ISSUE TITLE
Use "Make nearby luggages wait" hotkey cause game crash

### ISSUE THREAD

**Issue by StarskyXIII** [GizmoTheMoonPig/luggage#24]
### Forge or Fabric

Forge

### Mod Version

1.5.2

### Client Log

https://mclo.gs/MaCPwwL

### Crash Report (if applicable)

https://mclo.gs/JSCAuaD

### Bug Description

When use "ALT + `" to make nearby luggages wait, game will crash

### Steps to Reproduce

1.Enter the Singleplayer World or Server
2.Press "Alt + `" key
3.Game crash

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by aryst0krat** [comment]
Can confirm this is happening to me in Stoneblock 1.5.0. Normal whistle works fine, but alt+` hard crashes the game.

**Comment by GizmoTheMoonPig** [comment]
I forgot to register the packet needed for the command in 1.18 like an idiot. Just pushed a fix for it, will have a new build on github as soon as I can. Thank you for the report!
