### ISSUE TITLE
[1.19.2] Sometimes after cleaning and subsequent delivery of luggage into the world, it disappears

### ISSUE THREAD

**Issue by DrSigma4164** [GizmoTheMoonPig/luggage#25]
### Forge or Fabric

Forge

### Mod Version

1.5.2

### Client Log

https://gist.github.com/dd12341379cc0a367a2e768d8a40f9bb.git

### Bug Description

Sometimes, after I pick up luggage to come from hell to the normal world, for example, or another case where I pick it up and then try to put it to take resources from it, the moment I put it, it disappears, neither in the inventory nor there is no essence in the world. 
And this does not happen every time, but only sometimes. I was able to at least roughly repeat this, if you hold down the shift and put and take luggage into the inventory in a row, then it will disappear after a couple of tries.

### Steps to Reproduce

I'm not sure how to reproduce it, but it arrived like this:
1) take the luggage in your hands, you can take it with any items inside, but it is not important
2) with the shift pressed, put luggage in the world and pick it up, and after a while it will disappear. (and you can press the key once every 3 seconds, I checked it, that is, it is not a bug from the fact that you click quickly)

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This is... odd, to say the very least. Im not able to reproduce this myself (although im using just Luggage itself to test this, there could potentially be some mod conflict at play here) and nothing seems out of the ordinary in the log you sent. Not sure where to go with this, but i'll look into it further.

**Comment by DrSigma4164** [comment]
Well, if it is a conflict of mods, then here is my modpack on which I play and where it happens. If he helps you, I will be glad.
[1.19-1.8.zip](https://github.com/GizmoTheMoonPig/luggage/files/10390238/1.19-1.8.zip)

**Comment by DrSigma4164** [comment]
Oh, I found the reason. Spawn optimization mod, namely Adaptive Performance Tweaks: Spawn, as you can see in the screenshot below, it blocks if more than 16 mobs, I tried to increase this value, but it still reaches this limit, and without this mod, there will be noticeable lags, but can you add your chest to exclusions for this mod or something?
![image](https://user-images.githubusercontent.com/93322905/211763239-3cd44a47-a6a5-4c1d-841d-9c4f2637bcc6.png)

**Comment by GizmoTheMoonPig** [comment]
Took a quick peek into its config and found that if you add the mob to the spawnAllowList, you shouldn't have the issue anymore. Simply just add `luggage:luggage` to the config and the issue should fix itself. I'm not seeing any way for me to automatically define this behavior, but it's 3am right now so I may be missing something. I'll check again this afternoon. I may have to a github ticket for them to add it automatically, we'll see. 
In general I usually recommend that people avoid performance mods, as most of them will cause interesting issues like this. I'm glad this one allows the player to control how it works a bit but this still shouldn't be default behavior. 
Thank you for troubleshooting this further, and I'm sorry I haven't been much if a help lol
