### ISSUE TITLE
[Suggestion] Compatibility with the Domestication Innovation mod, which will allow teleporting from unloaded fragments

### ISSUE THREAD

**Issue by DrSigma4164** [GizmoTheMoonPig/luggage#26]
### The Suggestion

There is a [Domestication Innovation](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation) mod that adds various improvements to the animals you have domesticated and also to those compatible with this mod. One improvement is the Wayward Lantern, which allows all tamed animals, or those compatible with this mod, to teleport from unloaded chunks to this lantern, and then to the player.
So if you made it compatible with this mod, not completely, but at least with this item/block, it would allow me not to be afraid that I, for example, would lose my luggage after dying for thousands of blocks.

I'm not sure exactly how to do it, but the author of this mod writes on his page, for this you need:
"_If you are a mod dev and want to make sure Domestication Innovation works out of the box for your mod, remember to make sure your tameable mob's class extends TameableAnimal._"

### Why Should It Be in the Mod?

First of all, as I wrote above, it would help not to lose luggage after death for thousands of blocks.
Also, it is not rare for me that I just quickly move around the area, sometimes luggage hangs or gets stuck, I don’t know, but when I turn around to take resources from it, I don’t find it, it also doesn’t get called, because the chunks in which it is was, disembarked, and I need to go back for him.
There are many more reasons, but they all follow in one way or another from the ones written above.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
ive switched Luggage to extend TamableAnimal. I dont exactly remember why I didnt do this in the first place, but I guess it doesnt matter. IT should now work fine with DI

**Comment by DrSigma4164** [comment]
Now there is compatibility, but when I pick up luggage and then put it again, Collar Tags from Domestication Innovation, which is used to use fascinating, disappears ... I'm not sure whether it could be just fixed, but I would be glad if you were tried to do.
