### ISSUE TITLE
[Suggestion] Command / Item / Method to tell Luggage to stay where he is.

### ISSUE THREAD

**Issue by Darkona** [GizmoTheMoonPig/luggage#27]
### The Suggestion

Sometimes Luggage will be annoying by moving where you are building. The suggestion is to add a method to tell him to stay put, like wolves and cats and parrots.

### Why Should It Be in the Mod?

Luggage is amazingly useful, but sometimes you might need him to stay still while you use him for storage while building or other tasks.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I added a whistle command to make all Luggages you own nearby to sit and wait in 1.5. The keybind is ALT + ` by default, but you can change it in the controls menu if theres a conflict with some other keybind. Pressing the keybind again will let them wander freely.
