### ISSUE TITLE
Sound Assets Not in Mono

### ISSUE THREAD

**Issue by Darkosto** [GizmoTheMoonPig/luggage#3]
Hello!

Thanks for making this mod, I've been having a great time with it so far. One thing I did find is the audio assets are all in Stereo, which means the range on all sounds will be much farther and louder than all other sounds in the game. If you convert your existing sounds from Stereo into Mono this issue will be fixed.

Thanks again!
Darkosto

**Comment by GizmoTheMoonPig** [comment]
I pushed fixes for this on both 1.18 and 1.19, curseforge builds will soon be available. Thank you for letting me know about this!
