### ISSUE TITLE
[Suggestion] Add ways to quickly empty Luggage.

### ISSUE THREAD

**Issue by kalutro** [GizmoTheMoonPig/luggage#32]
### The Suggestion

Allow player to Sneak + Use a Luggage on an inventory to deposit the items from the Luggage into the target inventory.
Or... allow it to be used like a Bundle such that Using it in the air will dump the contents on the ground.

Really, just any way to quickly empty the little fellas.

### Why Should It Be in the Mod?

Luggage is fun to use. Manually emptying two dozen Luggage is not fun.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I genuinely liked this suggestion so much that I added both. The inventory dump thing will work on all modded inventories too, tested it just to make sure. I'll get an update out soon-ish, just have 1 more thing I'd like to do. Thanks for the awesome suggestion <3
