### ISSUE TITLE
Inventory dissappears on relog

### ISSUE THREAD

**Issue by jmadarg** [GizmoTheMoonPig/luggage#35]
### Forge or Fabric

NeoForge 1.21.1

### Mod Version

1.6.7

### Client Log

https://gist.github.com/jmadarg/ee96aea498db80c3d67b89aa2a2b563e#file-luggagetest-latest-log

### Bug Description

While playing on an modded server (NeoForge 21.1.41, MC 1.21.1) I noticed that if I had anything in my Luggage and disconnected then connected again, the inventory of the luggage would get wiped. 

I then tested on a singleplayer world with the same pack and had the same issue. I noticed in the provided latest.log that in line 1990 it says ```[Server thread/ERROR] [net.minecraft.world.item.ItemStack/]: Tried to load invalid item: 'No key id in MapLike[{Slot:12b}]'``` with similar messages in the following lines

I'm also sharing this, my debug.log https://gist.github.com/jmadarg/d97df93067f049cf105dba68882fde83

### Steps to Reproduce

1. Join a world/server
2. Get and place a luggage
3. Leave the world/server
4. Join the world/server once more
5. Luggage's inventory is gone

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by jmadarg** [comment]
I just tested something I didn't think about earlier. If you grab the luggage instead of leaving it as entity in the world, it does keep it's inventory.

**Comment by GizmoTheMoonPig** [comment]
fixed in af0e8f7, will upload a new build shortly
