### ISSUE TITLE
[NeoForge 1.21.1] Luggage's Inventory Clears when Going through a Portal

### ISSUE THREAD

**Issue by Flexico** [GizmoTheMoonPig/luggage#38]
### Forge or Fabric

NeoForge

### Mod Version

1.6.7

### Client Log

https://gist.github.com/Flexico/1c214024766ab2b94ebd1124d50c0898

### Bug Description

When I push a luggage through a portal (Nether, Aether, etc) the contents get erased!

### Steps to Reproduce

Put stuff into Luggage
Luggage go through Portal
Luggage no longer has stuff.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Uh oh! I was unfortunately able to replicate this with just the mod installed so its definitely something bad on my end. Just from looking at the logs it seems like items are not saving correctly, but I will look into this and get a fix out as soon as I can
