### ISSUE TITLE
[NeoForge 1.21.1] Crash Cleared Luggage Inventories

### ISSUE THREAD

**Issue by Flexico** [GizmoTheMoonPig/luggage#39]
### Forge or Fabric

Neoforge

### Mod Version

1.6.7

### Client Log

https://gist.github.com/Flexico/a23d73921d2bce5500363cb99dc1b8fd

### Crash Report (if applicable)

https://gist.github.com/Flexico/5fbe4794a1bc0be94b0009b4efb91e08

### Bug Description

It's me again! This time the game crashed while I was in the middle of a Trial Chamber, and when I relogged my luggages were empty! Thankfully I put the most precious treasures in my ender chest. I haven't been able to reproduce the crash, but the crash log said something about the Aether, and I'm pretty sure I had my inventory open at the time.

### Steps to Reproduce

Unable to reproduce

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
yeah luckily luggage didnt cause the crash but the inventory wipe is the same problem as the portal issue. Luggage doesnt save its inventory properly as an entity so if you do something that would trigger it to save its data (such as crashing or even relogging) its inventory will be wiped. I will push the fixed build to CF ASAP

**Comment by GizmoTheMoonPig** [comment]
Its approved already! https://www.curseforge.com/minecraft/mc-mods/luggage/files/5935753
You shouldnt have to worry about inventories being wiped anymore. This also contains the fix for ender luggage that you reported a while ago as well
