### ISSUE TITLE
Seems currently incompatible with forge 41.0.98

### ISSUE THREAD

**Issue by Carnis** [GizmoTheMoonPig/luggage#9]
For the sake of troubleshooting, I've done a fresh install of forge, and only using Luggage mod.
Mod File: luggage-1.4.1.jar
        Failure message: Luggage (luggage) has failed to load correctly
                java.lang.reflect.InvocationTargetException: null
        Mod Version: 1.4.1
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.NoSuchFieldError: ENTITIES
I'm sure this will work out when FML has a stable release.
Do feel free to just close this issue as it's more of a heads up that the FML beta seems to be bugging with luggage at the moment

**Comment by GizmoTheMoonPig** [comment]
yeah, this is because I still have yet to update the mod to newer forge versions. I'll go do that real fast

**Comment by GizmoTheMoonPig** [comment]
fixed in 1de2eb73650fecb232a87295329a1d13c3b84617, I'll have a curseforge build up shortly. appreciate the report!
